"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'English (US)' | 'Spanish' | 'French' | 'German' | 'Japanese';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simplified translations for the Settings page to start
const translations: Record<Language, Record<string, string>> = {
  'English (US)': {
    'settings.title': 'Account Portal',
    'settings.subtitle': 'Manage your digital footprint and fine-tune your family tree experience.',
    'settings.syncChanges': 'Sync Changes',
    'settings.tab.identity': 'My Identity',
    'settings.tab.visuals': 'Visuals',
    'settings.tab.alerts': 'Alerts',
    'settings.tab.security': 'Security',
    'settings.tab.regional': 'Regional',
    'settings.profile.title': 'Identity Profile',
    'settings.profile.desc': 'Set your public identity and profile credentials.',
    'settings.profile.name': 'Full Display Name',
    'settings.profile.phone': 'Contact Phone',
    'settings.profile.bio': 'Personal Bio',
    'settings.status.title': 'Account Status',
    'settings.appearance.title': 'Visual Styles',
    'settings.appearance.desc': 'Personalize the interface for your environment.',
    'settings.notifications.title': 'Alert Gateway',
    'settings.notifications.desc': 'Configure how you want to be notified of family events.',
    'settings.security.title': 'Shield Protocols',
    'settings.security.desc': 'Manage your access keys and security parameters.',
    'settings.preferences.title': 'Regional Config',
    'settings.preferences.desc': 'Configure your local interface environment.',
    'settings.termination.title': 'Nuclear Option',
    'settings.termination.desc': 'Permanent, irreversible data destruction.',
    'nav.navigation': 'Navigation',
    'nav.trees': 'My Family Trees',
    'nav.wall': 'Family Wall',
    'nav.notifications': 'Notifications',
    'nav.admin': 'Admin',
    'nav.accessRequests': 'Access Requests',
    'nav.reviewProposals': 'Review Proposals',
    'nav.mergeRequests': 'Merge Requests',
    'nav.profileClaims': 'Profile Claims',
    'nav.deletionRequests': 'Deletion Requests',
    'nav.manageInvites': 'Manage Invites',
    'nav.accountSettings': 'Account Settings',
    'nav.signOut': 'Sign Out',
    'header.dashboard': 'Dashboard',
    'header.familyTree': 'Family Tree',
    'header.notifications': 'Notifications',
    'header.accountSettings': 'Account Settings',
    'header.accessRequests': 'Access Requests',
    'header.treeInvitations': 'Tree Invitations',
    'header.relationshipProposals': 'Relationship Proposals',
    'dashboard.welcome': 'Welcome, {name}',
    'dashboard.subtitle': 'Manage your family trees, permissions, and historical records.',
    'dashboard.stats.activeTrees': 'Active Trees',
    'dashboard.stats.members': 'Members',
    'dashboard.stats.lastUpdate': 'Last Update',
    'dashboard.recentMemories': 'Recent Memories',
    'dashboard.familyTrees': 'Family Trees',
    'dashboard.newTree': 'New Tree',
    'dashboard.tree.created': 'Created {date}',
    'dashboard.tree.openTree': 'Open Tree',
    'dashboard.tree.rename': 'Rename',
    'dashboard.tree.delete': 'Delete',
    'dashboard.noTrees.title': 'No family trees yet',
    'dashboard.noTrees.subtitle': 'Start documenting your family history by creating your first tree.',
    'dashboard.noTrees.button': 'Create Your First Tree',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.tree.pending': 'Pending',
    'memories.title': 'Family Wall',
    'memories.subtitle': 'A shared space for milestones, stories, and photos. Preserve your heritage together.',
    'memories.add': 'Add Memory',
    'memories.loadingTrees': 'Loading trees...',
    'memories.selectTree': 'Select Tree',
    'memories.searchPlaceholder': 'Search memories...',
    'memories.filter.all': 'All',
    'memories.filter.milestone': 'Milestone',
    'memories.filter.story': 'Story',
    'memories.filter.photo': 'Photo',
    'memories.noMemories.title': 'No memories found',
    'memories.noMemories.searchSubtitle': 'Try adjusting your filters or search terms.',
    'memories.noMemories.emptySubtitle': 'Be the first to capture a family memory in this tree!',
    'memories.noMemories.button': 'Add Your First Memory',
    'role.admin': 'Admin',
    'role.editor': 'Editor',
    'role.viewer': 'Viewer',
    'role.pending': 'Pending',
    'notifications.title': 'Notifications',
    'notifications.unreadCount': '{count} unread messages',
    'notifications.markAllRead': 'Mark All as Read',
    'notifications.deleteAll': 'Delete All',
    'notifications.loading': 'Loading notifications...',
    'notifications.noNotifications.title': 'No notifications yet',
    'notifications.noNotifications.subtitle': "You're all caught up! Check back later.",
    'notifications.noNotifications.button': 'Go to Dashboard',
    'notifications.new': 'New',
    'notifications.readAt': 'Read {date}',
    'layout.accessRestricted': 'Access Restricted',
    'layout.noPermission': "You don't have permission to view this page.",
    'layout.loadingWorkspace': 'Loading your workspace...',
    'tree.loading': 'Fetching Tree Metadata…',
    'admin.accessRequests.title': 'Access Requests',
    'admin.accessRequests.subtitle': 'Manage who can join your family tree and their permission levels. New members and role upgrades appear here.',
    'admin.selectTree': 'Select Tree',
    'admin.selectTree.desc': 'Manage members for the selected workspace',
    'admin.chooseTree': 'Choose a tree...',
    'admin.upgrade': 'Upgrade',
    'admin.requested': 'Requested: {role}',
    'admin.current': 'Current: {role}',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.noRequests.title': 'No pending requests',
    'admin.noRequests.subtitle': 'When new family members ask to join your tree, they will show up here for approval.',
    'admin.invitations.title': 'Tree Invitations',
    'admin.invitations.subtitle': 'Create secure links to invite your relatives. Each link is valid for 7 days and requires your approval before they can join.',
    'admin.invitations.targetTree': 'Target Family Tree',
    'admin.invitations.targetTree.desc': 'Select which family workspace you want to create secure invitation links for.',
    'admin.invitations.selectToGenerate': 'Select a tree above to generate invitations.',
    'admin.invitations.selectToView': 'Select a tree above to view active invitations.',
    'admin.invitations.generate': 'Generate',
    'admin.invitations.link': '{role} Link',
    'admin.invitations.activeLinks': 'Active Links',
    'admin.invitations.expires': 'Expires {date}',
    'admin.invitations.desc.member': 'Can add people and propose relationships.',
    'admin.invitations.desc.viewer': 'Read-only access to the family tree.',
    'admin.invitations.desc.admin': 'Full control over tree and invitations.',
    'admin.invitations.copy': 'Copy',
    'admin.invitations.copied': 'Copied',
    'admin.invitations.noLinks': 'No active invitation links for this tree. Generate one above.',
    'admin.management.title': 'Tree Management',
    'admin.management.subtitle': 'Review and verify changes proposed by tree members.',
    'admin.management.sourceWorkspace': 'Source Workspace',
    'admin.management.sourceWorkspace.desc': 'Select the family tree you want to review proposals for.',
    'admin.management.tab.relationships': 'Relationships',
    'admin.management.tab.merges': 'Merges',
    'admin.management.tab.claims': 'Claims',
    'admin.management.tab.deletions': 'Deletions',
    'admin.management.proposed': 'Proposed {date} by {user}',
    'admin.management.label.subject': 'Subject',
    'admin.management.label.target': 'Target',
    'admin.management.label.source': 'Source (To be deleted)',
    'admin.management.label.destination': 'Destination (To keep)',
    'admin.management.mergeInto': 'Merge Into',
    'admin.management.profileClaimed': 'Profile being claimed',
    'admin.management.requestingUser': 'Requesting User',
    'admin.management.targetRemoval': 'Target for Removal',
    'admin.management.deletionWarning': 'Approval will permanently remove this profile and all its connections.',
    'admin.management.allCaughtUp': 'All caught up!',
    'admin.management.noProposals': 'There are no pending {type} proposals to review for this tree.',
    'admin.claims.title': 'Profile Claims',
    'admin.claims.subtitle': 'Review requests from users who want to link their account to an existing profile in the family tree.',
    'admin.claims.selectTree': 'Select Tree',
    'admin.claims.selectTree.desc': 'Review claims for the selected workspace',
    'admin.claims.chooseTree': 'Choose a tree...',
    'admin.claims.wantsToClaim': 'wants to claim',
    'admin.claims.requested': 'Requested {date}',
    'admin.claims.noRequests.title': 'No pending claim requests',
    'admin.claims.noRequests.subtitle': 'When users request to claim a profile in your tree, they will show up here for verification.',
    'role.member': 'Member',
    'relationship.parent': 'Parent',
    'relationship.child': 'Child',
    'relationship.spouse': 'Spouse',
    'relationship.sibling': 'Sibling',
    'notification.access_request_approved.title': 'Welcome to the Family Tree',
    'notification.access_request_approved.message': 'Your request to join as a {role} has been approved.',
    'notification.access_request_rejected.title': 'Access Request Rejected',
    'notification.access_request_rejected.message': 'Your request to join as a {role} was rejected.',
    'notification.access_request_pending.title.upgrade': 'Role Upgrade Request',
    'notification.access_request_pending.title.join': 'New Access Request',
    'notification.access_request_pending.upgrade_message': 'A user is requesting to upgrade from {currentRole} to {requestedRole}',
    'notification.access_request_pending.join_message': 'A new user is requesting to join your family tree as a {role}',
    'notification.deletion_proposal_pending.title': 'Deletion Request',
    'notification.deletion_proposal_pending.message': 'A deletion has been proposed for {name}',
    'notification.deletion_approved.title': 'Deletion Request Approved',
    'notification.deletion_approved.message': 'Your request to delete a profile has been approved.',
    'notification.deletion_rejected.title': 'Deletion Request Rejected',
    'notification.deletion_rejected.message': 'Your request to delete a profile was rejected.',
    'notification.claim_request_pending.title': 'Profile Claim Request',
    'notification.claim_request_pending.message': 'A user is requesting to claim the profile of {name}',
    'notification.claim_approved.title': 'Profile Claim Approved',
    'notification.claim_approved.message': 'Your request to claim a profile has been approved.',
    'notification.claim_rejected.title': 'Profile Claim Rejected',
    'notification.claim_rejected.message': 'Your request to claim a profile was rejected.',
    'notification.merge_proposal_pending.title': 'Merge Request',
    'notification.merge_proposal_pending.message': 'A merge has been proposed for {source} into {target}',
    'notification.merge_approved.title': 'Merge Request Approved',
    'notification.merge_approved.message': 'Your request to merge profiles has been approved.',
    'notification.merge_rejected.title': 'Merge Request Rejected',
    'notification.merge_rejected.message': 'Your request to merge profiles was rejected.',
    'notification.permission_granted.title': 'Permissions Granted',
    'notification.permission_granted.message': 'You have been granted {permissionType} rights on a profile.',
    'notification.relationship_pending.title': 'New Relationship Proposal',
    'notification.relationship_pending.message': 'A new {relationshipType} relationship has been proposed in your tree.',
    'notification.relationship_approved.title': 'Relationship Approved',
    'notification.relationship_approved.message': 'Your proposed {relationshipType} relationship has been approved.',
    'notification.relationship_rejected.title': 'Relationship Rejected',
    'notification.relationship_rejected.message': 'Your proposed {relationshipType} relationship was rejected: {reason}',
  },
  'Spanish': {
    'settings.title': 'Portal de Cuenta',
    'settings.subtitle': 'Administra tu huella digital y ajusta tu experiencia en el árbol genealógico.',
    'settings.syncChanges': 'Sincronizar Cambios',
    'settings.tab.identity': 'Mi Identidad',
    'settings.tab.visuals': 'Visuales',
    'settings.tab.alerts': 'Alertas',
    'settings.tab.security': 'Seguridad',
    'settings.tab.regional': 'Regional',
    'settings.profile.title': 'Perfil de Identidad',
    'settings.profile.desc': 'Establece tu identidad pública y credenciales de perfil.',
    'settings.profile.name': 'Nombre Completo',
    'settings.profile.phone': 'Teléfono de Contacto',
    'settings.profile.bio': 'Biografía Personal',
    'settings.status.title': 'Estado de la Cuenta',
    'settings.appearance.title': 'Estilos Visuales',
    'settings.appearance.desc': 'Personaliza la interfaz para tu entorno.',
    'settings.notifications.title': 'Puerta de Alertas',
    'settings.notifications.desc': 'Configura cómo quieres ser notificado de eventos familiares.',
    'settings.security.title': 'Protocolos de Escudo',
    'settings.security.desc': 'Administra tus llaves de acceso y parámetros de seguridad.',
    'settings.preferences.title': 'Configuración Regional',
    'settings.preferences.desc': 'Configura tu entorno de interfaz local.',
    'settings.termination.title': 'Opción Nuclear',
    'settings.termination.desc': 'Destrucción de datos permanente e irreversible.',
    'nav.navigation': 'Navegación',
    'nav.trees': 'Mis Árboles',
    'nav.wall': 'Muro Familiar',
    'nav.notifications': 'Notificaciones',
    'nav.admin': 'Admin',
    'nav.accessRequests': 'Solicitudes de Acceso',
    'nav.reviewProposals': 'Revisar Propuestas',
    'nav.mergeRequests': 'Solicitudes de Fusión',
    'nav.profileClaims': 'Reclamos de Perfil',
    'nav.deletionRequests': 'Solicitudes de Eliminación',
    'nav.manageInvites': 'Gestionar Invitaciones',
    'nav.accountSettings': 'Ajustes de Cuenta',
    'nav.signOut': 'Cerrar Sesión',
    'header.dashboard': 'Tablero',
    'header.familyTree': 'Árbol Genealógico',
    'header.notifications': 'Notificaciones',
    'header.accountSettings': 'Ajustes de Cuenta',
    'header.accessRequests': 'Solicitudes de Acceso',
    'header.treeInvitations': 'Invitaciones al Árbol',
    'header.relationshipProposals': 'Propuestas de Relación',
    'dashboard.welcome': 'Bienvenido/a, {name}',
    'dashboard.subtitle': 'Administra tus árboles genealógicos, permisos y registros históricos.',
    'dashboard.stats.activeTrees': 'Árboles Activos',
    'dashboard.stats.members': 'Miembros',
    'dashboard.stats.lastUpdate': 'Última Actualización',
    'dashboard.recentMemories': 'Memorias Recientes',
    'dashboard.familyTrees': 'Árboles Genealógicos',
    'dashboard.newTree': 'Nuevo Árbol',
    'dashboard.tree.created': 'Creado el {date}',
    'dashboard.tree.openTree': 'Abrir Árbol',
    'dashboard.tree.rename': 'Renombrar',
    'dashboard.tree.delete': 'Eliminar',
    'dashboard.noTrees.title': 'Aún no hay árboles genealógicos',
    'dashboard.noTrees.subtitle': 'Comienza a documentar tu historia familiar creando tu primer árbol.',
    'dashboard.noTrees.button': 'Crea tu primer árbol',
    'dashboard.loading': 'Cargando tablero...',
    'dashboard.tree.pending': 'Pendiente',
    'memories.title': 'Muro Familiar',
    'memories.subtitle': 'Un espacio compartido para hitos, historias y fotos. Conserva tu legado juntos.',
    'memories.add': 'Agregar Recuerdo',
    'memories.loadingTrees': 'Cargando árboles...',
    'memories.selectTree': 'Seleccionar Árbol',
    'memories.searchPlaceholder': 'Buscar recuerdos...',
    'memories.filter.all': 'Todo',
    'memories.filter.milestone': 'Hito',
    'memories.filter.story': 'Historia',
    'memories.filter.photo': 'Foto',
    'memories.noMemories.title': 'No se encontraron recuerdos',
    'memories.noMemories.searchSubtitle': 'Intenta ajustar tus filtros o términos de búsqueda.',
    'memories.noMemories.emptySubtitle': '¡Sé el primero en capturar un recuerdo familiar en este árbol!',
    'memories.noMemories.button': 'Agregar tu primer recuerdo',
    'role.admin': 'Administrador',
    'role.editor': 'Editor',
    'role.viewer': 'Lector',
    'role.pending': 'Pendiente',
    'notifications.title': 'Notificaciones',
    'notifications.unreadCount': '{count} mensajes sin leer',
    'notifications.markAllRead': 'Marcar todo como leído',
    'notifications.deleteAll': 'Eliminar todo',
    'notifications.loading': 'Cargando notificaciones...',
    'notifications.noNotifications.title': 'Aún no hay notificaciones',
    'notifications.noNotifications.subtitle': '¡Estás al día! Vuelve más tarde.',
    'notifications.noNotifications.button': 'Ir al Tablero',
    'notifications.new': 'Nuevo',
    'notifications.readAt': 'Leído el {date}',
    'layout.accessRestricted': 'Acceso Restringido',
    'layout.noPermission': 'No tienes permiso para ver esta página.',
    'layout.loadingWorkspace': 'Cargando tu espacio de trabajo...',
    'tree.loading': 'Obteniendo metadatos del árbol...',
    'admin.accessRequests.title': 'Solicitudes de Acceso',
    'admin.accessRequests.subtitle': 'Administra quién puede unirse a tu árbol genealógico y sus niveles de permiso. Los nuevos miembros y las actualizaciones de rol aparecen aquí.',
    'admin.selectTree': 'Seleccionar Árbol',
    'admin.selectTree.desc': 'Administrar miembros para el espacio de trabajo seleccionado',
    'admin.chooseTree': 'Elige un árbol...',
    'admin.upgrade': 'Actualizar',
    'admin.requested': 'Solicitado: {role}',
    'admin.current': 'Actual: {role}',
    'admin.approve': 'Aprobar',
    'admin.reject': 'Rechazar',
    'admin.noRequests.title': 'No hay solicitudes pendientes',
    'admin.noRequests.subtitle': 'Cuando nuevos miembros de la familia soliciten unirse a tu árbol, aparecerán aquí para su aprobación.',
    'admin.invitations.title': 'Invitaciones al Árbol',
    'admin.invitations.subtitle': 'Crea enlaces seguros para invitar a tus familiares. Cada enlace es válido por 7 días y requiere tu aprobación antes de que puedan unirse.',
    'admin.invitations.targetTree': 'Árbol Genealógico de Destino',
    'admin.invitations.targetTree.desc': 'Selecciona para qué espacio de trabajo familiar deseas crear enlaces de invitación seguros.',
    'admin.invitations.selectToGenerate': 'Selecciona un árbol arriba para generar invitaciones.',
    'admin.invitations.selectToView': 'Selecciona un árbol arriba para ver las invitaciones activas.',
    'admin.invitations.generate': 'Generar',
    'admin.invitations.link': 'Enlace de {role}',
    'admin.invitations.activeLinks': 'Enlaces Activos',
    'admin.invitations.expires': 'Expira el {date}',
    'admin.invitations.desc.member': 'Puede agregar personas y proponer relaciones.',
    'admin.invitations.desc.viewer': 'Acceso de solo lectura al árbol genealógico.',
    'admin.invitations.desc.admin': 'Control total sobre el árbol y las invitaciones.',
    'admin.invitations.copy': 'Copiar',
    'admin.invitations.copied': 'Copiado',
    'admin.invitations.noLinks': 'No hay enlaces de invitación activos para este árbol. Genera uno arriba.',
    'admin.management.title': 'Gestión del Árbol',
    'admin.management.subtitle': 'Revisa y verifica los cambios propuestos por los miembros del árbol.',
    'admin.management.sourceWorkspace': 'Espacio de Trabajo de Origen',
    'admin.management.sourceWorkspace.desc': 'Selecciona el árbol genealógico para el cual deseas revisar las propuestas.',
    'admin.management.tab.relationships': 'Relaciones',
    'admin.management.tab.merges': 'Fusiones',
    'admin.management.tab.claims': 'Reclamaciones',
    'admin.management.tab.deletions': 'Eliminaciones',
    'admin.management.proposed': 'Propuesto el {date} por {user}',
    'admin.management.label.subject': 'Sujeto',
    'admin.management.label.target': 'Objetivo',
    'admin.management.label.source': 'Origen (Se eliminará)',
    'admin.management.label.destination': 'Destino (Se conservará)',
    'admin.management.mergeInto': 'Fusionar en',
    'admin.management.profileClaimed': 'Perfil reclamado',
    'admin.management.requestingUser': 'Usuario Solicitante',
    'admin.management.targetRemoval': 'Objetivo de Eliminación',
    'admin.management.deletionWarning': 'La aprobación eliminará permanentemente este perfil y todas sus conexiones.',
    'admin.management.allCaughtUp': '¡Todo al día!',
    'admin.management.noProposals': 'No hay propuestas de {type} pendientes para revisar en este árbol.',
    'admin.claims.title': 'Reclamaciones de Perfil',
    'admin.claims.subtitle': 'Revisa las solicitudes de usuarios que quieren vincular su cuenta a un perfil existente en el árbol genealógico.',
    'admin.claims.selectTree': 'Seleccionar Árbol',
    'admin.claims.selectTree.desc': 'Revisar reclamaciones del espacio de trabajo seleccionado',
    'admin.claims.chooseTree': 'Elige un árbol...',
    'admin.claims.wantsToClaim': 'quiere reclamar',
    'admin.claims.requested': 'Solicitado {date}',
    'admin.claims.noRequests.title': 'No hay solicitudes de reclamación pendientes',
    'admin.claims.noRequests.subtitle': 'Cuando los usuarios soliciten reclamar un perfil en tu árbol, aparecerán aquí para su verificación.',
    'role.member': 'Miembro',
    'relationship.parent': 'Padre/Madre',
    'relationship.child': 'Hijo/a',
    'relationship.spouse': 'Cónyuge',
    'relationship.sibling': 'Hermano/a',
    'notification.access_request_approved.title': 'Bienvenido al Árbol Genealógico',
    'notification.access_request_approved.message': 'Tu solicitud para unirte como {role} ha sido aprobada.',
    'notification.access_request_rejected.title': 'Solicitud de Acceso Rechazada',
    'notification.access_request_rejected.message': 'Tu solicitud para unirte como {role} fue rechazada.',
    'notification.access_request_pending.title.upgrade': 'Solicitud de Actualización de Rol',
    'notification.access_request_pending.title.join': 'Nueva Solicitud de Acceso',
    'notification.access_request_pending.upgrade_message': 'Un usuario solicita actualizar de {currentRole} a {requestedRole}',
    'notification.access_request_pending.join_message': 'Un nuevo usuario solicita unirse a tu árbol genealógico como {role}',
    'notification.deletion_proposal_pending.title': 'Solicitud de Eliminación',
    'notification.deletion_proposal_pending.message': 'Se ha propuesto la eliminación de {name}',
    'notification.deletion_approved.title': 'Solicitud de Eliminación Aprobada',
    'notification.deletion_approved.message': 'Tu solicitud para eliminar un perfil ha sido aprobada.',
    'notification.deletion_rejected.title': 'Solicitud de Eliminación Rechazada',
    'notification.deletion_rejected.message': 'Tu solicitud para eliminar un perfil fue rechazada.',
    'notification.claim_request_pending.title': 'Solicitud de Reclamación de Perfil',
    'notification.claim_request_pending.message': 'Un usuario solicita reclamar el perfil de {name}',
    'notification.claim_approved.title': 'Reclamación de Perfil Aprobada',
    'notification.claim_approved.message': 'Tu solicitud para reclamar un perfil ha sido aprobada.',
    'notification.claim_rejected.title': 'Reclamación de Perfil Rechazada',
    'notification.claim_rejected.message': 'Tu solicitud para reclamar un perfil fue rechazada.',
    'notification.merge_proposal_pending.title': 'Solicitud de Fusión',
    'notification.merge_proposal_pending.message': 'Se ha propuesto fusionar a {source} en {target}',
    'notification.merge_approved.title': 'Solicitud de Fusión Aprobada',
    'notification.merge_approved.message': 'Tu solicitud para fusionar perfiles ha sido aprobada.',
    'notification.merge_rejected.title': 'Solicitud de Fusión Rechazada',
    'notification.merge_rejected.message': 'Tu solicitud para fusionar perfiles fue rechazada.',
    'notification.permission_granted.title': 'Permisos Concedidos',
    'notification.permission_granted.message': 'Se te han concedido derechos de {permissionType} en un perfil.',
    'notification.relationship_pending.title': 'Nueva Propuesta de Relación',
    'notification.relationship_pending.message': 'Se ha propuesto una nueva relación de {relationshipType} en tu árbol.',
    'notification.relationship_approved.title': 'Relación Aprobada',
    'notification.relationship_approved.message': 'Tu propuesta de relación de {relationshipType} ha sido aprobada.',
    'notification.relationship_rejected.title': 'Relación Rechazada',
    'notification.relationship_rejected.message': 'Tu propuesta de relación de {relationshipType} fue rechazada: {reason}',
  },
  'French': {
    'settings.title': 'Portail du Compte',
    'settings.subtitle': 'Gérez votre empreinte numérique et affinez votre expérience de l\'arbre généalogique.',
    'settings.syncChanges': 'Synchroniser les modifications',
    'settings.tab.identity': 'Mon Identité',
    'settings.tab.visuals': 'Visuels',
    'settings.tab.alerts': 'Alertes',
    'settings.tab.security': 'Sécurité',
    'settings.tab.regional': 'Régional',
    'settings.profile.title': 'Profil d\'Identité',
    'settings.profile.desc': 'Définissez votre identité publique et vos identifiants de profil.',
    'settings.profile.name': 'Nom complet',
    'settings.profile.phone': 'Téléphone de contact',
    'settings.profile.bio': 'Biographie personnelle',
    'settings.status.title': 'État du compte',
    'settings.appearance.title': 'Styles visuels',
    'settings.appearance.desc': 'Personnalisez l\'interface pour votre environnement.',
    'settings.notifications.title': 'Passerelle d\'alerte',
    'settings.notifications.desc': 'Configurez la manière dont vous souhaitez être informé des événements familiaux.',
    'settings.security.title': 'Protocoles de bouclier',
    'settings.security.desc': 'Gérez vos clés d\'accès et vos paramètres de sécurité.',
    'settings.preferences.title': 'Configuration régionale',
    'settings.preferences.desc': 'Configurez votre environnement d\'interface locale.',
    'settings.termination.title': 'Option nucléaire',
    'settings.termination.desc': 'Destruction permanente et irréversible des données.',
    'nav.navigation': 'Navigation',
    'nav.trees': 'Mes Arbres',
    'nav.wall': 'Mur Familial',
    'nav.notifications': 'Notifications',
    'nav.admin': 'Admin',
    'nav.accessRequests': 'Demandes d\'Accès',
    'nav.reviewProposals': 'Réviser Propositions',
    'nav.mergeRequests': 'Demandes de Fusion',
    'nav.profileClaims': 'Revendications Profil',
    'nav.deletionRequests': 'Demandes de Suppression',
    'nav.manageInvites': 'Gérer Invitations',
    'nav.accountSettings': 'Paramètres Compte',
    'nav.signOut': 'Déconnexion',
    'header.dashboard': 'Tableau de Bord',
    'header.familyTree': 'Arbre Généalogique',
    'header.notifications': 'Notifications',
    'header.accountSettings': 'Paramètres Compte',
    'header.accessRequests': 'Demandes d\'Accès',
    'header.treeInvitations': 'Invitations Arbre',
    'header.relationshipProposals': 'Propositions de Relation',
    'dashboard.welcome': 'Bienvenue, {name}',
    'dashboard.subtitle': 'Gérez vos arbres généalogiques, vos autorisations et vos archives historiques.',
    'dashboard.stats.activeTrees': 'Arbres Actifs',
    'dashboard.stats.members': 'Membres',
    'dashboard.stats.lastUpdate': 'Dernière Mise à Jour',
    'dashboard.recentMemories': 'Souvenirs Récents',
    'dashboard.familyTrees': 'Arbres Généalogiques',
    'dashboard.newTree': 'Nouvel Arbre',
    'dashboard.tree.created': 'Créé le {date}',
    'dashboard.tree.openTree': 'Ouvrir l\'Arbre',
    'dashboard.tree.rename': 'Renommer',
    'dashboard.tree.delete': 'Supprimer',
    'dashboard.noTrees.title': 'Pas encore d\'arbre généalogique',
    'dashboard.noTrees.subtitle': 'Commencez à documenter l\'histoire de votre famille en créant votre premier arbre.',
    'dashboard.noTrees.button': 'Créer votre premier arbre',
    'dashboard.loading': 'Chargement du tableau de bord...',
    'dashboard.tree.pending': 'En attente',
    'memories.title': 'Mur Familial',
    'memories.subtitle': 'Un espace partagé pour les jalons, les histoires et les photos. Préservez votre héritage ensemble.',
    'memories.add': 'Ajouter un Souvenir',
    'memories.loadingTrees': 'Chargement des arbres...',
    'memories.selectTree': 'Sélectionner un Arbre',
    'memories.searchPlaceholder': 'Rechercher des souvenirs...',
    'memories.filter.all': 'Tout',
    'memories.filter.milestone': 'Étape',
    'memories.filter.story': 'Histoire',
    'memories.filter.photo': 'Photo',
    'memories.noMemories.title': 'Aucun souvenir trouvé',
    'memories.noMemories.searchSubtitle': 'Essayez d’ajuster vos filtres ou vos termes de recherche.',
    'memories.noMemories.emptySubtitle': 'Soyez le premier à capturer un souvenir familial dans cet arbre !',
    'memories.noMemories.button': 'Ajouter votre premier souvenir',
    'role.admin': 'Administrateur',
    'role.editor': 'Éditeur',
    'role.viewer': 'Spectateur',
    'role.pending': 'En attente',
    'notifications.title': 'Notifications',
    'notifications.unreadCount': '{count} messages non lus',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.deleteAll': 'Tout supprimer',
    'notifications.loading': 'Chargement des notifications...',
    'notifications.noNotifications.title': 'Pas encore de notifications',
    'notifications.noNotifications.subtitle': 'Vous êtes à jour ! Revenez plus tard.',
    'notifications.noNotifications.button': 'Aller au Tableau de Bord',
    'notifications.new': 'Nouveau',
    'notifications.readAt': 'Lu le {date}',
    'layout.accessRestricted': 'Accès Restreint',
    'layout.noPermission': "Vous n'avez pas l'autorisation de voir cette page.",
    'layout.loadingWorkspace': 'Chargement de votre espace de travail...',
    'tree.loading': "Récupération des métadonnées de l'arbre...",
    'admin.accessRequests.title': 'Demandes d\'Accès',
    'admin.accessRequests.subtitle': 'Gérez qui peut rejoindre votre arbre généalogique et leurs niveaux de permission. Les nouveaux membres et les mises à niveau de rôle apparaissent ici.',
    'admin.selectTree': 'Sélectionner l\'Arbre',
    'admin.selectTree.desc': 'Gérer les membres pour l\'espace de travail sélectionné',
    'admin.chooseTree': 'Choisir un arbre...',
    'admin.upgrade': 'Mettre à niveau',
    'admin.requested': 'Demandé : {role}',
    'admin.current': 'Actuel : {role}',
    'admin.approve': 'Approuver',
    'admin.reject': 'Rejeter',
    'admin.noRequests.title': 'Aucune demande en attente',
    'admin.noRequests.subtitle': 'Lorsque de nouveaux membres de la famille demandent à rejoindre votre arbre, ils apparaîtront ici pour approbation.',
    'admin.invitations.title': 'Invitations Arbre',
    'admin.invitations.subtitle': 'Créez des liens sécurisés pour inviter vos proches. Chaque lien est valide pendant 7 jours et nécessite votre approbation avant qu\'ils ne puissent rejoindre.',
    'admin.invitations.targetTree': 'Arbre Généalogique Cible',
    'admin.invitations.targetTree.desc': 'Sélectionnez l\'espace de travail familial pour lequel vous souhaitez créer des liens d\'invitation sécurisés.',
    'admin.invitations.selectToGenerate': 'Sélectionnez un arbre ci-dessus pour générer des invitations.',
    'admin.invitations.selectToView': 'Sélectionnez un arbre ci-dessus pour voir les invitations actives.',
    'admin.invitations.generate': 'Générer',
    'admin.invitations.link': 'Lien {role}',
    'admin.invitations.activeLinks': 'Liens Actifs',
    'admin.invitations.expires': 'Expire le {date}',
    'admin.invitations.desc.member': 'Peut ajouter des personnes et proposer des relations.',
    'admin.invitations.desc.viewer': 'Accès en lecture seule à l\'arbre généalogique.',
    'admin.invitations.desc.admin': 'Contrôle total sur l\'arbre et les invitations.',
    'admin.invitations.copy': 'Copier',
    'admin.invitations.copied': 'Copié',
    'admin.invitations.noLinks': 'Aucun lien d\'invitation actif pour cet arbre. Générez-en un ci-dessus.',
    'admin.management.title': 'Gestion de l\'Arbre',
    'admin.management.subtitle': 'Examinez et vérifiez les modifications proposées par les membres de l\'arbre.',
    'admin.management.sourceWorkspace': 'Espace de Travail Source',
    'admin.management.sourceWorkspace.desc': 'Sélectionnez l\'arbre généalogique pour lequel vous souhaitez examiner les propositions.',
    'admin.management.tab.relationships': 'Relations',
    'admin.management.tab.merges': 'Fusions',
    'admin.management.tab.claims': 'Revendications',
    'admin.management.tab.deletions': 'Suppressions',
    'admin.management.proposed': 'Proposé le {date} par {user}',
    'admin.management.label.subject': 'Sujet',
    'admin.management.label.target': 'Cible',
    'admin.management.label.source': 'Source (Sera supprimé)',
    'admin.management.label.destination': 'Destination (À conserver)',
    'admin.management.mergeInto': 'Fusionner dans',
    'admin.management.profileClaimed': 'Profil revendiqué',
    'admin.management.requestingUser': 'Utilisateur Demandeur',
    'admin.management.targetRemoval': 'Cible pour Suppression',
    'admin.management.deletionWarning': 'L\'approbation supprimera définitivement ce profil et toutes ses connexions.',
    'admin.management.allCaughtUp': 'Tout est à jour !',
    'admin.management.noProposals': 'Il n\'y a pas de proposition de {type} en attente pour cet arbre.',
    'admin.claims.title': 'Revendications de Profil',
    'admin.claims.subtitle': 'Examinez les demandes des utilisateurs qui souhaitent lier leur compte à un profil existant dans l\'arbre généalogique.',
    'admin.claims.selectTree': 'Sélectionner un Arbre',
    'admin.claims.selectTree.desc': 'Examiner les revendications de l\'espace de travail sélectionné',
    'admin.claims.chooseTree': 'Choisir un arbre...',
    'admin.claims.wantsToClaim': 'souhaite revendiquer',
    'admin.claims.requested': 'Demandé le {date}',
    'admin.claims.noRequests.title': 'Aucune demande de revendication en attente',
    'admin.claims.noRequests.subtitle': 'Lorsque des utilisateurs demandent à revendiquer un profil dans votre arbre, ils apparaîtront ici pour vérification.',
    'role.member': 'Membre',
    'relationship.parent': 'Parent',
    'relationship.child': 'Enfant',
    'relationship.spouse': 'Conjoint',
    'relationship.sibling': 'Frère/Sœur',
    'notification.access_request_approved.title': 'Bienvenue dans l\'Arbre Généalogique',
    'notification.access_request_approved.message': 'Votre demande d\'adhésion en tant que {role} a été approuvée.',
    'notification.access_request_rejected.title': 'Demande d\'Accès Rejetée',
    'notification.access_request_rejected.message': 'Votre demande d\'adhésion en tant que {role} a été rejetée.',
    'notification.access_request_pending.title.upgrade': 'Demande de Mise à Niveau de Rôle',
    'notification.access_request_pending.title.join': 'Nouvelle Demande d\'Accès',
    'notification.access_request_pending.upgrade_message': 'Un utilisateur demande à passer de {currentRole} à {requestedRole}',
    'notification.access_request_pending.join_message': 'Un nouvel utilisateur demande à rejoindre votre arbre généalogique en tant que {role}',
    'notification.deletion_proposal_pending.title': 'Demande de Suppression',
    'notification.deletion_proposal_pending.message': 'Une suppression a été proposée pour {name}',
    'notification.deletion_approved.title': 'Demande de Suppression Approuvée',
    'notification.deletion_approved.message': 'Votre demande de suppression de profil a été approuvée.',
    'notification.deletion_rejected.title': 'Demande de Suppression Rejetée',
    'notification.deletion_rejected.message': 'Votre demande de suppression de profil a été rejetée.',
    'notification.claim_request_pending.title': 'Demande de Revendication de Profil',
    'notification.claim_request_pending.message': 'Un utilisateur demande à revendiquer le profil de {name}',
    'notification.claim_approved.title': 'Revendication de Profil Approuvée',
    'notification.claim_approved.message': 'Votre demande de revendication de profil a été approuvée.',
    'notification.claim_rejected.title': 'Revendication de Profil Rejetée',
    'notification.claim_rejected.message': 'Votre demande de revendication de profil a été rejetée.',
    'notification.merge_proposal_pending.title': 'Demande de Fusion',
    'notification.merge_proposal_pending.message': 'Une fusion a été proposée pour {source} dans {target}',
    'notification.merge_approved.title': 'Demande de Fusion Approuvée',
    'notification.merge_approved.message': 'Votre demande de fusion de profils a été approuvée.',
    'notification.merge_rejected.title': 'Demande de Fusion Rejetée',
    'notification.merge_rejected.message': 'Votre demande de fusion de profils a été rejetée.',
    'notification.permission_granted.title': 'Autorisations Accordées',
    'notification.permission_granted.message': 'Des droits de {permissionType} vous ont été accordés sur un profil.',
    'notification.relationship_pending.title': 'Nouvelle Proposition de Relation',
    'notification.relationship_pending.message': 'Une nouvelle relation de {relationshipType} a été proposée dans votre arbre.',
    'notification.relationship_approved.title': 'Relation Approuvée',
    'notification.relationship_approved.message': 'Votre proposition de relation de {relationshipType} a été approuvée.',
    'notification.relationship_rejected.title': 'Relation Rejetée',
    'notification.relationship_rejected.message': 'Votre proposition de relation de {relationshipType} a été rejetée : {reason}',
  },
  'German': {
    'settings.title': 'Kontoportal',
    'settings.subtitle': 'Verwalten Sie Ihren digitalen Fußabdruck und verfeinern Sie Ihr Stammbaumerlebnis.',
    'settings.syncChanges': 'Änderungen synchronisieren',
    'settings.tab.identity': 'Meine Identität',
    'settings.tab.visuals': 'Visuals',
    'settings.tab.alerts': 'Benachrichtigungen',
    'settings.tab.security': 'Sicherheit',
    'settings.tab.regional': 'Regional',
    'settings.profile.title': 'Identitätsprofil',
    'settings.profile.desc': 'Legen Sie Ihre öffentliche Identität und Ihre Profilanmeldedaten fest.',
    'settings.profile.name': 'Vollständiger Anzeigename',
    'settings.profile.phone': 'Kontakt-Telefon',
    'settings.profile.bio': 'Persönliche Biografie',
    'settings.status.title': 'Kontostatus',
    'settings.appearance.title': 'Visuelle Stile',
    'settings.appearance.desc': 'Personalisieren Sie die Benutzeroberfläche für Ihre Umgebung.',
    'settings.notifications.title': 'Benachrichtigungsgateway',
    'settings.notifications.desc': 'Konfigurieren Sie, wie Sie über Familienereignisse informiert werden möchten.',
    'settings.security.title': 'Schutzprotokolle',
    'settings.security.desc': 'Verwalten Sie Ihre Zugriffsschlüssel und Sicherheitsparameter.',
    'settings.preferences.title': 'Regionale Konfiguration',
    'settings.preferences.desc': 'Konfigurieren Sie Ihre lokale Schnittstellenumgebung.',
    'settings.termination.title': 'Nukleare Option',
    'settings.termination.desc': 'Dauerhafte, unwiderrufliche Datenvernichtung.',
    'nav.navigation': 'Navigation',
    'nav.trees': 'Meine Bäume',
    'nav.wall': 'Familienwand',
    'nav.notifications': 'Benachrichtigungen',
    'nav.admin': 'Admin',
    'nav.accessRequests': 'Zugriffsanfragen',
    'nav.reviewProposals': 'Vorschläge prüfen',
    'nav.mergeRequests': 'Zusammenführungsanfragen',
    'nav.profileClaims': 'Profilansprüche',
    'nav.deletionRequests': 'Löschanfragen',
    'nav.manageInvites': 'Einladungen verwalten',
    'nav.accountSettings': 'Kontoeinstellungen',
    'nav.signOut': 'Abmelden',
    'header.dashboard': 'Dashboard',
    'header.familyTree': 'Stammbaum',
    'header.notifications': 'Benachrichtigungen',
    'header.accountSettings': 'Kontoeinstellungen',
    'header.accessRequests': 'Zugriffsanfragen',
    'header.treeInvitations': 'Baumeinladungen',
    'header.relationshipProposals': 'Beziehungsvorschläge',
    'dashboard.welcome': 'Willkommen, {name}',
    'dashboard.subtitle': 'Verwalten Sie Ihre Stammbäume, Berechtigungen und historischen Aufzeichnungen.',
    'dashboard.stats.activeTrees': 'Aktive Bäume',
    'dashboard.stats.members': 'Mitglieder',
    'dashboard.stats.lastUpdate': 'Letztes Update',
    'dashboard.recentMemories': 'Neueste Erinnerungen',
    'dashboard.familyTrees': 'Stammbäume',
    'dashboard.newTree': 'Neuer Baum',
    'dashboard.tree.created': 'Erstellt am {date}',
    'dashboard.tree.openTree': 'Baum öffnen',
    'dashboard.tree.rename': 'Umbenennen',
    'dashboard.tree.delete': 'Löschen',
    'dashboard.noTrees.title': 'Noch keine Stammbäume',
    'dashboard.noTrees.subtitle': 'Beginnen Sie mit der Dokumentation Ihrer Familiengeschichte, indem Sie Ihren ersten Baum erstellen.',
    'dashboard.noTrees.button': 'Erstellen Sie Ihren ersten Baum',
    'dashboard.loading': 'Dashboard wird geladen...',
    'dashboard.tree.pending': 'Ausstehend',
    'memories.title': 'Familienwand',
    'memories.subtitle': 'Ein gemeinsamer Raum für Meilensteine, Geschichten und Fotos. Bewahren Sie Ihr Erbe gemeinsam.',
    'memories.add': 'Erinnerung hinzufügen',
    'memories.loadingTrees': 'Bäume werden geladen...',
    'memories.selectTree': 'Baum auswählen',
    'memories.searchPlaceholder': 'Erinnerungen suchen...',
    'memories.filter.all': 'Alle',
    'memories.filter.milestone': 'Meilenstein',
    'memories.filter.story': 'Geschichte',
    'memories.filter.photo': 'Foto',
    'memories.noMemories.title': 'Keine Erinnerungen gefunden',
    'memories.noMemories.searchSubtitle': 'Versuchen Sie, Ihre Filter oder Suchbegriffe anzupassen.',
    'memories.noMemories.emptySubtitle': 'Seien Sie der Erste, der eine Familienerinnerung in diesem Baum festhält!',
    'memories.noMemories.button': 'Erste Erinnerung hinzufügen',
    'role.admin': 'Administrator',
    'role.editor': 'Editor',
    'role.viewer': 'Betrachter',
    'role.pending': 'Ausstehend',
    'notifications.title': 'Benachrichtigungen',
    'notifications.unreadCount': '{count} ungelesene Nachrichten',
    'notifications.markAllRead': 'Alle als gelesen markieren',
    'notifications.deleteAll': 'Alle löschen',
    'notifications.loading': 'Benachrichtigungen werden geladen...',
    'notifications.noNotifications.title': 'Noch keine Benachrichtigungen',
    'notifications.noNotifications.subtitle': 'Sie sind auf dem neuesten Stand! Schauen Sie später wieder vorbei.',
    'notifications.noNotifications.button': 'Zum Dashboard',
    'notifications.new': 'Neu',
    'notifications.readAt': 'Gelesen am {date}',
    'layout.accessRestricted': 'Zugriff eingeschränkt',
    'layout.noPermission': 'Sie haben keine Berechtigung, diese Seite anzuzeigen.',
    'layout.loadingWorkspace': 'Ihr Arbeitsbereich wird geladen...',
    'tree.loading': 'Stammbaum-Metadaten werden abgerufen...',
    'admin.accessRequests.title': 'Zugriffsanfragen',
    'admin.accessRequests.subtitle': 'Verwalten Sie, wer Ihrem Stammbaum beitreten kann, und deren Berechtigungsstufen. Neue Mitglieder und Rollen-Upgrades werden hier angezeigt.',
    'admin.selectTree': 'Baum auswählen',
    'admin.selectTree.desc': 'Mitglieder für den ausgewählten Arbeitsbereich verwalten',
    'admin.chooseTree': 'Wählen Sie einen Baum...',
    'admin.upgrade': 'Upgrade',
    'admin.requested': 'Angefordert: {role}',
    'admin.current': 'Aktuell: {role}',
    'admin.approve': 'Genehmigen',
    'admin.reject': 'Ablehnen',
    'admin.noRequests.title': 'Keine ausstehenden Anfragen',
    'admin.noRequests.subtitle': 'Wenn neue Familienmitglieder darum bitten, Ihrem Baum beizutreten, werden sie hier zur Genehmigung angezeigt.',
    'admin.invitations.title': 'Baumeinladungen',
    'admin.invitations.subtitle': 'Erstellen Sie sichere Links, um Ihre Verwandten einzuladen. Jeder Link ist 7 Tage lang gültig und erfordert Ihre Genehmigung, bevor sie beitreten können.',
    'admin.invitations.targetTree': 'Ziel-Stammbaum',
    'admin.invitations.targetTree.desc': 'Wählen Sie aus, für welchen Familienarbeitsbereich Sie sichere Einladungslinks erstellen möchten.',
    'admin.invitations.selectToGenerate': 'Wählen Sie oben einen Baum aus, um Einladungen zu generieren.',
    'admin.invitations.selectToView': 'Wählen Sie oben einen Baum aus, um aktive Einladungen anzuzeigen.',
    'admin.invitations.generate': 'Generieren',
    'admin.invitations.link': '{role}-Link',
    'admin.invitations.activeLinks': 'Aktive Links',
    'admin.invitations.expires': 'Ablaufdatum: {date}',
    'admin.invitations.desc.member': 'Kann Personen hinzufügen und Beziehungen vorschlagen.',
    'admin.invitations.desc.viewer': 'Schreibgeschützter Zugriff auf den Stammbaum.',
    'admin.invitations.desc.admin': 'Volle Kontrolle über Stammbaum und Einladungen.',
    'admin.invitations.copy': 'Kopieren',
    'admin.invitations.copied': 'Kopiert',
    'admin.invitations.noLinks': 'Keine aktiven Einladungslinks für diesen Baum. Generieren Sie oben einen.',
    'admin.management.title': 'Stammbaum-Verwaltung',
    'admin.management.subtitle': 'Überprüfen und verifizieren Sie die von Stammbaummitgliedern vorgeschlagenen Änderungen.',
    'admin.management.sourceWorkspace': 'Quell-Arbeitsbereich',
    'admin.management.sourceWorkspace.desc': 'Wählen Sie den Stammbaum aus, für den Sie Vorschläge überprüfen möchten.',
    'admin.management.tab.relationships': 'Beziehungen',
    'admin.management.tab.merges': 'Zusammenführungen',
    'admin.management.tab.claims': 'Ansprüche',
    'admin.management.tab.deletions': 'Löschungen',
    'admin.management.proposed': 'Vorgeschlagen am {date} von {user}',
    'admin.management.label.subject': 'Subjekt',
    'admin.management.label.target': 'Ziel',
    'admin.management.label.source': 'Quelle (Wird gelöscht)',
    'admin.management.label.destination': 'Ziel (Behalten)',
    'admin.management.mergeInto': 'Zusammenführen in',
    'admin.management.profileClaimed': 'Profil wird beansprucht',
    'admin.management.requestingUser': 'Anfordernder Benutzer',
    'admin.management.targetRemoval': 'Ziel zur Entfernung',
    'admin.management.deletionWarning': 'Die Genehmigung wird dieses Profil und all seine Verbindungen dauerhaft entfernen.',
    'admin.management.allCaughtUp': 'Alles erledigt!',
    'admin.management.noProposals': 'Es stehen keine {type}-Vorschläge zur Überprüfung für diesen Baum aus.',
    'admin.claims.title': 'Profilansprüche',
    'admin.claims.subtitle': 'Überprüfen Sie Anfragen von Benutzern, die ihr Konto mit einem vorhandenen Profil im Stammbaum verknüpfen möchten.',
    'admin.claims.selectTree': 'Baum auswählen',
    'admin.claims.selectTree.desc': 'Ansprüche für den ausgewählten Arbeitsbereich überprüfen',
    'admin.claims.chooseTree': 'Wählen Sie einen Baum...',
    'admin.claims.wantsToClaim': 'möchte beanspruchen',
    'admin.claims.requested': 'Angefordert am {date}',
    'admin.claims.noRequests.title': 'Keine ausstehenden Anspruchsanfragen',
    'admin.claims.noRequests.subtitle': 'Wenn Benutzer ein Profil in Ihrem Baum beanspruchen möchten, werden sie hier zur Überprüfung angezeigt.',
    'role.member': 'Mitglied',
    'relationship.parent': 'Elternteil',
    'relationship.child': 'Kind',
    'relationship.spouse': 'Ehepartner',
    'relationship.sibling': 'Geschwisterkind',
    'notification.access_request_approved.title': 'Willkommen im Stammbaum',
    'notification.access_request_approved.message': 'Ihre Anfrage auf Beitritt als {role} wurde genehmigt.',
    'notification.access_request_rejected.title': 'Zugriffsanfrage abgelehnt',
    'notification.access_request_rejected.message': 'Ihre Anfrage auf Beitritt als {role} wurde abgelehnt.',
    'notification.access_request_pending.title.upgrade': 'Rollen-Upgrade-Anfrage',
    'notification.access_request_pending.title.join': 'Neue Zugriffsanfrage',
    'notification.access_request_pending.upgrade_message': 'Ein Benutzer möchte von {currentRole} auf {requestedRole} upgraden',
    'notification.access_request_pending.join_message': 'Ein neuer Benutzer möchte Ihrem Stammbaum als {role} beitreten',
    'notification.deletion_proposal_pending.title': 'Löschanfrage',
    'notification.deletion_proposal_pending.message': 'Eine Löschung wurde vorgeschlagen für {name}',
    'notification.deletion_approved.title': 'Löschanfrage genehmigt',
    'notification.deletion_approved.message': 'Ihre Anfrage zur Löschung eines Profils wurde genehmigt.',
    'notification.deletion_rejected.title': 'Löschanfrage abgelehnt',
    'notification.deletion_rejected.message': 'Ihre Anfrage zur Löschung eines Profils wurde abgelehnt.',
    'notification.claim_request_pending.title': 'Profilanspruchs-Anfrage',
    'notification.claim_request_pending.message': 'Ein Benutzer möchte das Profil von {name} beanspruchen',
    'notification.claim_approved.title': 'Profilanspruch genehmigt',
    'notification.claim_approved.message': 'Ihre Anfrage zur Beanspruchung eines Profils wurde genehmigt.',
    'notification.claim_rejected.title': 'Profilanspruch abgelehnt',
    'notification.claim_rejected.message': 'Ihre Anfrage zur Beanspruchung eines Profils wurde abgelehnt.',
    'notification.merge_proposal_pending.title': 'Zusammenführungsanfrage',
    'notification.merge_proposal_pending.message': 'Eine Zusammenführung wurde vorgeschlagen für {source} in {target}',
    'notification.merge_approved.title': 'Zusammenführungsanfrage genehmigt',
    'notification.merge_approved.message': 'Ihre Anfrage zur Zusammenführung von Profilen wurde genehmigt.',
    'notification.merge_rejected.title': 'Zusammenführungsanfrage abgelehnt',
    'notification.merge_rejected.message': 'Ihre Anfrage zur Zusammenführung von Profilen wurde abgelehnt.',
    'notification.permission_granted.title': 'Berechtigungen erteilt',
    'notification.permission_granted.message': 'Ihnen wurden {permissionType}-Rechte an einem Profil erteilt.',
    'notification.relationship_pending.title': 'Neuer Beziehungsvorschlag',
    'notification.relationship_pending.message': 'Ein neuer Beziehungsvorschlag für {relationshipType} wurde in Ihrem Baum eingereicht.',
    'notification.relationship_approved.title': 'Beziehungsvorschlag genehmigt',
    'notification.relationship_approved.message': 'Ihr Beziehungsvorschlag für {relationshipType} wurde genehmigt.',
    'notification.relationship_rejected.title': 'Beziehungsvorschlag abgelehnt',
    'notification.relationship_rejected.message': 'Ihr Beziehungsvorschlag für {relationshipType} wurde abgelehnt: {reason}',
  },
  'Japanese': {
    'settings.title': 'アカウントポータル',
    'settings.subtitle': 'デジタルフットプリントを管理し、家系図の体験を微調整します。',
    'settings.syncChanges': '変更を同期',
    'settings.tab.identity': 'マイアイデンティティ',
    'settings.tab.visuals': 'ビジュアル',
    'settings.tab.alerts': 'アラート',
    'settings.tab.security': 'セキュリティ',
    'settings.tab.regional': '地域設定',
    'settings.profile.title': 'アイデンティティプロファイル',
    'settings.profile.desc': '公開アイデンティティとプロファイル資格情報を設定します。',
    'settings.profile.name': 'フルネーム',
    'settings.profile.phone': '連絡先電話番号',
    'settings.profile.bio': '個人バイオ',
    'settings.status.title': 'アカウントステータス',
    'settings.appearance.title': 'ビジュアルスタイル',
    'settings.appearance.desc': '環境に合わせてインターフェースをパーソナライズします。',
    'settings.notifications.title': 'アラートゲートウェイ',
    'settings.notifications.desc': '家族のイベントの通知方法を設定します。',
    'settings.security.title': 'シールドプロトコル',
    'settings.security.desc': 'アクセスキーとセキュリティパラメータを管理します。',
    'settings.preferences.title': '地域設定',
    'settings.preferences.desc': 'ローカルインターフェース環境を設定します。',
    'settings.termination.title': '核オプション',
    'settings.termination.desc': '恒久的で不可逆的なデータの破壊。',
    'nav.navigation': 'ナビゲーション',
    'nav.trees': 'マイツリー',
    'nav.wall': 'ファミリーウォール',
    'nav.notifications': '通知',
    'nav.admin': '管理者',
    'nav.accessRequests': 'アクセスリクエスト',
    'nav.reviewProposals': '提案の確認',
    'nav.mergeRequests': '統合リクエスト',
    'nav.profileClaims': 'プロフィール請求',
    'nav.deletionRequests': '削除リクエスト',
    'nav.manageInvites': '招待の管理',
    'nav.accountSettings': 'アカウント設定',
    'nav.signOut': 'サインアウト',
    'header.dashboard': 'ダッシュボード',
    'header.familyTree': '家系図',
    'header.notifications': '通知',
    'header.accountSettings': 'アカウント設定',
    'header.accessRequests': 'アクセスリクエスト',
    'header.treeInvitations': 'ツリーへの招待',
    'header.profileClaims': 'プロフィール請求',
    'header.relationshipProposals': '関係の提案',
    'dashboard.welcome': '{name} さん、ようこそ',
    'dashboard.subtitle': '家系図、アクセス権限、および歴史的記録を管理します。',
    'dashboard.stats.activeTrees': '有効なツリー',
    'dashboard.stats.members': 'メンバー',
    'dashboard.stats.lastUpdate': '最終更新',
    'dashboard.recentMemories': '最近の思い出',
    'dashboard.familyTrees': '家系図',
    'dashboard.newTree': '新しいツリー',
    'dashboard.tree.created': '{date} に作成',
    'dashboard.tree.openTree': 'ツリーを開く',
    'dashboard.tree.rename': '名前変更',
    'dashboard.tree.delete': '削除',
    'dashboard.noTrees.title': '家系図がまだありません',
    'dashboard.noTrees.subtitle': '最初のツリーを作成して、家族の歴史 of 家族の歴史の記録を開始しましょう。',
    'dashboard.noTrees.button': '最初のツリーを作成する',
    'dashboard.loading': 'ダッシュボードを読み込み中...',
    'dashboard.tree.pending': '保留中',
    'memories.title': 'ファミリーボード',
    'memories.subtitle': '節目、物語、写真を共有する場所です。家族の歴史を一緒に残しましょう。',
    'memories.add': '思い出を追加',
    'memories.loadingTrees': 'ツリーを読み込み中...',
    'memories.selectTree': 'ツリーを選択',
    'memories.searchPlaceholder': '思い出を検索...',
    'memories.filter.all': 'すべて',
    'memories.filter.milestone': '節目',
    'memories.filter.story': '物語',
    'memories.filter.photo': '写真',
    'memories.noMemories.title': '思い出が見つかりません',
    'memories.noMemories.searchSubtitle': 'フィルターや検索語を調整してみてください。',
    'memories.noMemories.emptySubtitle': 'このツリーで最初の家族の思い出を記録しましょう！',
    'memories.noMemories.button': '最初の思い出を追加',
    'role.admin': '管理者',
    'role.editor': '編集者',
    'role.viewer': '閲覧者',
    'role.pending': '保留中',
    'notifications.title': '通知',
    'notifications.unreadCount': '{count} 件の未読メッセージ',
    'notifications.markAllRead': 'すべて既読にする',
    'notifications.deleteAll': 'すべて削除',
    'notifications.loading': '通知を読み込み中...',
    'notifications.noNotifications.title': '通知はまだありません',
    'notifications.noNotifications.subtitle': 'すべて確認されました！後ほどご確認ください。',
    'notifications.noNotifications.button': 'ダッシュボードへ移動',
    'notifications.new': '新規',
    'notifications.readAt': '{date} に既読',
    'layout.accessRestricted': 'アクセス制限',
    'layout.noPermission': 'このページを表示する権限がありません。',
    'layout.loadingWorkspace': 'ワークスペースを読み込み中...',
    'tree.loading': 'ツリーのメタデータを取得中…',
    'admin.accessRequests.title': 'アクセスリクエスト',
    'admin.accessRequests.subtitle': '家系図への参加者とその権限レベルを管理します。新規メンバーおよびロールの昇格リクエストがここに表示されます。',
    'admin.selectTree': 'ツリー選択',
    'admin.selectTree.desc': '選択したワークスペース of メンバーを管理します',
    'admin.chooseTree': 'ツリーを選択してください...',
    'admin.upgrade': 'アップグレード',
    'admin.requested': 'リクエストされたロール: {role}',
    'admin.current': '現在のロール: {role}',
    'admin.approve': '承認',
    'admin.reject': '却下',
    'admin.noRequests.title': '保留中のリクエストはありません',
    'admin.noRequests.subtitle': '新しい家族メンバーがツリーへの参加をリクエストすると、承認のためにここに表示されます。',
    'admin.invitations.title': 'ツリーへの招待',
    'admin.invitations.subtitle': '親戚を招待するための安全なリンクを作成します。各リンクは7日間有効で、参加には管理者の承認が必要です。',
    'admin.invitations.targetTree': '対象家系図',
    'admin.invitations.targetTree.desc': '招待リンクを作成する対象の家族ワークスペースを選択します。',
    'admin.invitations.selectToGenerate': '招待を生成するには、上でツリーを選択してください。',
    'admin.invitations.selectToView': '有効な招待を表示するには、上でツリーを選択してください。',
    'admin.invitations.generate': '生成',
    'admin.invitations.link': '{role} リンク',
    'admin.invitations.activeLinks': '有効なリンク',
    'admin.invitations.expires': '有効期限 {date}',
    'admin.invitations.desc.member': 'メンバーを追加し、関係を提案できます。',
    'admin.invitations.desc.viewer': '家系図への読み取り専用アクセス。',
    'admin.invitations.desc.admin': 'ツリーと招待の完全な制御。',
    'admin.invitations.copy': 'コピー',
    'admin.invitations.copied': 'コピーされました',
    'admin.invitations.noLinks': 'このツリーの有効な招待リンクはありません。上で生成してください。',
    'admin.management.title': 'ツリー管理',
    'admin.management.subtitle': 'ツリーメンバーから提案された変更を確認・検証します。',
    'admin.management.sourceWorkspace': 'ソースワークスペース',
    'admin.management.sourceWorkspace.desc': '提案を確認したい家系図を選択します。',
    'admin.management.tab.relationships': '関係',
    'admin.management.tab.merges': '統合',
    'admin.management.tab.claims': 'プロフィール請求',
    'admin.management.tab.deletions': '削除',
    'admin.management.proposed': '{date} に {user} によって提案',
    'admin.management.label.subject': '主語',
    'admin.management.label.target': '対象',
    'admin.management.label.source': '統合元 (削除されます)',
    'admin.management.label.destination': '統合先 (残されます)',
    'admin.management.mergeInto': '統合先',
    'admin.management.profileClaimed': '請求対象のプロフィール',
    'admin.management.requestingUser': 'リクエストユーザー',
    'admin.management.targetRemoval': '削除対象',
    'admin.management.deletionWarning': '承認すると、このプロフィールとすべての接続が完全に削除されます。',
    'admin.management.allCaughtUp': 'すべて処理済みです！',
    'admin.management.noProposals': 'このツリーに保留中の {type} 提案はありません。',
    'admin.claims.title': 'プロフィール請求',
    'admin.claims.subtitle': '家系図内の既存プロフィールにアカウントをリンクしたいユーザーからのリクエストを確認します。',
    'admin.claims.selectTree': 'ツリーを選択',
    'admin.claims.selectTree.desc': '選択したワークスペースの請求を確認します',
    'admin.claims.chooseTree': 'ツリーを選択してください...',
    'admin.claims.wantsToClaim': 'を請求したい',
    'admin.claims.requested': '{date} にリクエスト',
    'admin.claims.noRequests.title': '保留中の請求リクエストはありません',
    'admin.claims.noRequests.subtitle': 'ユーザーがツリー内のプロフィールを請求すると、ここに表示されて確認できます。',
    'role.member': 'メンバー',
    'relationship.parent': '親',
    'relationship.child': '子',
    'relationship.spouse': '配偶者',
    'relationship.sibling': '兄弟姉妹',
    'notification.access_request_approved.title': '家系図へようこそ',
    'notification.access_request_approved.message': '{role} としての参加リクエストが承認されました。',
    'notification.access_request_rejected.title': 'アクセスリクエスト却下',
    'notification.access_request_rejected.message': '{role} としての参加リクエストが却下されました。',
    'notification.access_request_pending.title.upgrade': 'ロール昇格リクエスト',
    'notification.access_request_pending.title.join': '新規アクセスリクエスト',
    'notification.access_request_pending.upgrade_message': 'ユーザーが {currentRole} から {requestedRole} へのアップグレードをリクエストしています。',
    'notification.access_request_pending.join_message': '新しいユーザーが {role} としてあなたの家系図への参加をリクエストしています。',
    'notification.deletion_proposal_pending.title': '削除リクエスト',
    'notification.deletion_proposal_pending.message': '{name} の削除が提案されました。',
    'notification.deletion_approved.title': '削除リクエスト承認',
    'notification.deletion_approved.message': 'プロフィール削除リクエストが承認されました。',
    'notification.deletion_rejected.title': '削除リクエスト却下',
    'notification.deletion_rejected.message': 'プロフィール削除リクエストが却下されました。',
    'notification.claim_request_pending.title': 'プロフィール請求リクエスト',
    'notification.claim_request_pending.message': 'ユーザーが {name} のプロフィールの請求をリクエストしています。',
    'notification.claim_approved.title': 'プロフィール請求承認',
    'notification.claim_approved.message': 'プロフィール請求リクエストが承認されました。',
    'notification.claim_rejected.title': 'プロフィール請求却下',
    'notification.claim_rejected.message': 'プロフィール請求リクエストが却下されました。',
    'notification.merge_proposal_pending.title': '統合リクエスト',
    'notification.merge_proposal_pending.message': '{source} を {target} に統合する提案が出されています。',
    'notification.merge_approved.title': '統合リクエスト承認',
    'notification.merge_approved.message': 'プロフィール統合リクエストが承認されました。',
    'notification.merge_rejected.title': '統合リクエスト却下',
    'notification.merge_rejected.message': 'プロフィール統合リクエストが却下されました。',
    'notification.permission_granted.title': '権限付与',
    'notification.permission_granted.message': 'プロフィールに対する {permissionType} 権限が付与されました。',
    'notification.relationship_pending.title': '新規関係提案',
    'notification.relationship_pending.message': 'ツリー内に新しい {relationshipType} 関係が提案されました。',
    'notification.relationship_approved.title': '関係承認',
    'notification.relationship_approved.message': '提案された {relationshipType} 関係が承認されました。',
    'notification.relationship_rejected.title': '関係却下',
    'notification.relationship_rejected.message': '提案された {relationshipType} 関係が却下されました: {reason}',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('English (US)');

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
